### ISSUE TITLE
404 when clicking category links

### ISSUE THREAD

**Issue by hitjim** [mcrice123/morphic#3]
I get a 404 at https://mcrice123.github.io/categories/book1/ and https://mcrice123.github.io/categories/misc/

This was after clicking the respective category links as seen here
![image](https://user-images.githubusercontent.com/730506/36702380-7e65e10a-1b1c-11e8-8583-6d854d7e267a.png)

**Comment by mcrice123** [comment]
Sorry for not responding sooner. If you're referring to the links on the sidebar, I caught the bug and fixed it: https://github.com/mcrice123/morphic/commit/14c28b3fc64430baf0d52809d01b747aafb29f96

Thanks for letting me know!
